repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: check-case-conflict
  - id: check-merge-conflict

- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
  -   id: pyupgrade
      args: [--py39-plus]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
    - id: codespell
      args: [
        "--write-changes",
        "--ignore-words-list",
        "fo",
        "--skip",
        ".github/config.yml",
        ]
